name: All tests on PR

on:
  pull_request:
    branches:
      - main
      - 'feature/**'

jobs:
  run-rest-assured-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64

      - name: Install Maven dependencies
        run: mvn clean install -U


      - name: Run Rest Assured tests
        run: mvn test

      - name: Generate test artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: ./target/surefire-reports/
