on:
  pull_request:
    branches:
      - main
      - 'feature/**'

jobs:
  run-all-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64

      - name: Install Maven dependencies
        run: mvn clean install -U

      - name: Generate Cucumber Report
        run: mvn verify

      - name: Upload Cucumber Report
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: target/surefire-reports/cucumber-html-reports/overview-failures.html
